### PR TITLE
Fix #276: Startup error from Liquibase for Test Server

### LINKED ISSUE #276: Startup error from Liquibase for Test Server
Following error occurs when I build Test Server and deploy it to Tomcat:

```
Liquibase failed to start because no changelog could be found at 'classpath:/db/changelog/db.changelog-master.yaml'.
```

We should stick to easy to deploy artifacts, e.g. no additional steps should be required to run the war file on Tomcat other than configuration.

### PR DESCRIPTION
**Pull request by jandusil**
- Set liquibase deps only as optional with mvn profile

### CODE REVIEW

**Comment by jandusil** [comment]
Tested locally

image

**Review by banterCZ — CHANGES_REQUESTED** [review]
But when I enable the maven profile `liquibase`, I get the same error. I suppose that you are missing a property something like `spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml` Please do not add it to the `application.properties` but to `application-dev.properties` or `application-liquibase.properties`

**Comment by jandusil** [comment]
> But when I enable the maven profile `liquibase`, I get the same error. I suppose that you are missing a property something like `spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml` Please do not add it to the `application.properties` but to `application-dev.properties` or `application-liquibase.properties`

Apologies, i havent pushed the commit by mistake

**Review by banterCZ — APPROVED** [review]
Looks good.

**Review by romanstrobl — COMMENTED** [review]
Looks OK.

**Pull request merged**
